"""empty message

Revision ID: 633de7d0291e
Revises: 84e3b88204a2
Create Date: 2026-04-26 18:31:00.494241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633de7d0291e'
down_revision = '84e3b88204a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
